package store

import (
	"strings"
	"testing"
)

func TestEncryptTokenRoundTrip(t *testing.T) {
	const secret = "0123456789abcdef"
	const token = "fixture-token-中文"

	envelope, err := EncryptToken(token, secret)
	if err != nil {
		t.Fatalf("EncryptToken() error = %v", err)
	}
	parts := strings.Split(envelope, ":")
	if len(parts) != 3 || parts[0] != "v1" {
		t.Fatalf("EncryptToken() envelope = %q", envelope)
	}
	if len(parts[1]) != 16 { // 12 bytes encoded with unpadded base64url.
		t.Fatalf("EncryptToken() IV encoding length = %d, want 16", len(parts[1]))
	}

	decrypted, err := DecryptToken(envelope, secret)
	if err != nil {
		t.Fatalf("DecryptToken() error = %v", err)
	}
	if decrypted != token {
		t.Fatalf("DecryptToken() = %q, want %q", decrypted, token)
	}
}

func TestDecryptTokenAutoRunTSFixture(t *testing.T) {
	// Generated by Web Crypto AES-GCM with SHA-256("0123456789abcdef") and a
	// fixed nonce.  This guards compatibility with tokens already in D1.
	const envelope = "v1:AAECAwQFBgcICQoL:HQgyNhJPl2fQA0KTABACBhPdSH1pNHJKlG1njAc"

	got, err := DecryptToken(envelope, "0123456789abcdef")
	if err != nil {
		t.Fatalf("DecryptToken() error = %v", err)
	}
	if got != "fixture-token" {
		t.Fatalf("DecryptToken() = %q, want fixture-token", got)
	}
}

func TestTokenCryptoRejectsInvalidInput(t *testing.T) {
	if _, err := EncryptToken("token", "too-short"); err == nil {
		t.Fatal("EncryptToken() accepted a short encryption key")
	}
	if _, err := DecryptToken("v1:not-valid:not-valid", "0123456789abcdef"); err == nil {
		t.Fatal("DecryptToken() accepted a malformed envelope")
	}
	if _, err := DecryptToken("v1:AAECAwQFBgcICQoL:HQgyNhJPl2fQA0KTABACBhPdSH1pNHJKlG1njAc", "different-secret"); err == nil {
		t.Fatal("DecryptToken() accepted a wrong encryption key")
	}
}

func TestHashPhoneAndGenerateSessionKey(t *testing.T) {
	if got := HashPhone(" 13900000000 "); got != SHA256Hex("13900000000") {
		t.Fatalf("HashPhone() = %q, want SHA-256 of trimmed phone", got)
	}
	if got := HashPhone("   "); got != "" {
		t.Fatalf("HashPhone(empty) = %q, want empty", got)
	}
	first, err := GenerateSessionKey()
	if err != nil {
		t.Fatalf("GenerateSessionKey() error = %v", err)
	}
	second, err := GenerateSessionKey()
	if err != nil {
		t.Fatalf("GenerateSessionKey() second error = %v", err)
	}
	if len(first) != 43 || len(second) != 43 || first == second {
		t.Fatalf("GenerateSessionKey() = (%q, %q), want two distinct 32-byte URL-safe keys", first, second)
	}
}
