package store

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"strings"
)

const (
	cryptoEnvelopeVersion = "v1"
	cryptoIVSize          = 12
	minimumSecretLength   = 16
)

// EncryptToken encrypts an upstream token in the same v1 envelope used by
// AutoRun-ts: v1:<base64url(iv)>:<base64url(AES-GCM ciphertext)>.
// The key is SHA-256(SESSION_ENCRYPTION_KEY), matching the Web Crypto port.
func EncryptToken(token, secret string) (string, error) {
	key, err := deriveEncryptionKey(secret)
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("autorun store: create token cipher: %w", err)
	}
	gcm, err := cipher.NewGCMWithNonceSize(block, cryptoIVSize)
	if err != nil {
		return "", fmt.Errorf("autorun store: create token AEAD: %w", err)
	}
	iv := make([]byte, cryptoIVSize)
	if _, err := io.ReadFull(rand.Reader, iv); err != nil {
		return "", fmt.Errorf("autorun store: generate token nonce: %w", err)
	}
	ciphertext := gcm.Seal(nil, iv, []byte(token), nil)
	return strings.Join([]string{
		cryptoEnvelopeVersion,
		base64.RawURLEncoding.EncodeToString(iv),
		base64.RawURLEncoding.EncodeToString(ciphertext),
	}, ":"), nil
}

// DecryptToken decrypts a token envelope generated by EncryptToken or the
// existing AutoRun-ts worker.  Errors intentionally do not reveal whether a
// supplied secret, nonce, or ciphertext was incorrect.
func DecryptToken(envelope, secret string) (string, error) {
	key, err := deriveEncryptionKey(secret)
	if err != nil {
		return "", err
	}
	parts := strings.Split(envelope, ":")
	if len(parts) != 3 || parts[0] != cryptoEnvelopeVersion {
		return "", errors.New("autorun store: invalid token envelope")
	}
	iv, err := decodeBase64URL(parts[1])
	if err != nil || len(iv) != cryptoIVSize {
		return "", errors.New("autorun store: invalid token envelope")
	}
	ciphertext, err := decodeBase64URL(parts[2])
	if err != nil || len(ciphertext) == 0 {
		return "", errors.New("autorun store: invalid token envelope")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("autorun store: create token cipher: %w", err)
	}
	gcm, err := cipher.NewGCMWithNonceSize(block, cryptoIVSize)
	if err != nil {
		return "", fmt.Errorf("autorun store: create token AEAD: %w", err)
	}
	plaintext, err := gcm.Open(nil, iv, ciphertext, nil)
	if err != nil {
		return "", errors.New("autorun store: token decryption failed")
	}
	return string(plaintext), nil
}

// SHA256Hex returns a lowercase hexadecimal SHA-256 digest.
func SHA256Hex(value string) string {
	sum := sha256.Sum256([]byte(value))
	return fmt.Sprintf("%x", sum[:])
}

// HashPhone returns the digest stored for a phone number.  Empty phones do
// not represent an owner and therefore remain an empty string.
func HashPhone(phone string) string {
	phone = strings.TrimSpace(phone)
	if phone == "" {
		return ""
	}
	return SHA256Hex(phone)
}

// GenerateSessionKey creates the 32-byte URL-safe key used by HTTP clients.
func GenerateSessionKey() (string, error) {
	bytes := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, bytes); err != nil {
		return "", fmt.Errorf("autorun store: generate session key: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(bytes), nil
}

func deriveEncryptionKey(secret string) ([]byte, error) {
	if len(strings.TrimSpace(secret)) < minimumSecretLength {
		return nil, errors.New("autorun store: SESSION_ENCRYPTION_KEY is too short")
	}
	digest := sha256.Sum256([]byte(secret))
	return digest[:], nil
}

func decodeBase64URL(value string) ([]byte, error) {
	decoded, err := base64.RawURLEncoding.DecodeString(value)
	if err == nil {
		return decoded, nil
	}
	// Accept padded envelopes as a migration convenience; new values always
	// use RawURLEncoding, just like the TypeScript implementation.
	return base64.URLEncoding.DecodeString(value)
}
